### ISSUE TITLE
OpenReceiveChannelAck No channel with this PassThruPartyId

### ISSUE THREAD

**Issue by miguelsanzpardo** [chan-sccp/chan-sccp#370]
**Description**
[2017-01-31 09:25:10] ERROR[25094][C-000000d0] sccp_actions.c: SEPACA016FCFE60: (OpenReceiveChannelAck) No channel with this PassThruPartyId 4294962992 (callReference: 4303, callid: 4303)!
[2017-01-31 09:25:48] ERROR[25094][C-000000d0] sccp_actions.c: SEPACA016FCFE60: (OpenReceiveChannelAck) No channel with this PassThruPartyId 4294962982 (callReference: 4313, callid: 4313)!
Device:
devicetype=7911

**chan-sccp version:** Release: 4.3.0 develop - f08ac44M

**asterisk version:** 11.21.2

**Addition / Optional Information:**
- Problem started happening recently, didn't happen in an older version of Chan-SCCP: [Not sure]
- Problem can be reliably reproduced, doesn't happen randomly: [Not sure]
- Platform:
  - [32/64 Bit]
  - [Operating System]

**Comment by dkgroot** [comment]
Pushed a new branch 'issues/370' to correct the OpenReceiveChannelAck debug output.

It might just be that the user already ended the call, but we were still processing the RTP start request. 

If that is the cause (and we should see that when we increase the debug level), then we only have to reduce the debug output from ERROR to standard.

Please set "sccp debug core, channel, pbx" during testing of the patch, so that we can check if the call was already 'ended' when the error message was produced.

**Comment by miguelsanzpardo** [comment]
Sharing: (OpenReceiveChannelAck) No channel with this PassThruPartyId_Error
[Uploading (OpenReceiveChannelAck) No channel with this PassThruPartyId_Error.txt…]()
